version: "3"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
  gateway:
    depends_on:
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./gateway
    volumes:
      - /app/node_modules
      - ./gateway:/app
    environment:
      - WORKSPACE_CLIENT_URL=workspace-client:3001
      - MAIN_CLIENT_URL=main-client:3002
      - API_URL=api:3000
    ports:
      - "80:80"
  api:
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=900
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DATABASE=${POSTGRES_DB}
      - DATABASE_HOST=postgres
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - "3000:3000"
  workspace-client:
    build:
      dockerfile: Dockerfile.dev
      context: ./workspace-client
    volumes:
      - /app/node_modules
      - ./workspace-client:/app
    environment:
      - PORT=3001
      - VUE_APP_BASE_URL=localhost
    ports:
      - "3001:3001"
    stdin_open: true
  main-client:
    build:
      dockerfile: Dockerfile.dev
      context: ./main-client
    volumes:
      - /app/node_modules
      - ./main-client:/app
    environment:
      - PORT=3002
      - VUE_APP_BASE_URL=localhost
      - VUE_APP_GRECAPTCHA_SITE=${GRECAPTCHA_SITE}
    ports:
      - "3002:3002"
    stdin_open: true
