apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: srn-pw-tls
spec:
  secretName: srn-pw-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - '*.srn.pw'
  - 'srn.pw'
