apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: srn-pw-tls
spec:
  secretName: srn-pw
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.srn.pw'
  dnsNames:
    - srn.pw
    - '*.srn.pw'
  acme:
    config:
      - dns01:
          provider: cloudflare
        domains:
          - srn.pw
          - '*.srn.pw'
