apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "webmaster@firerock.io"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
      cloudflare:
        email: webmaster@aidanglickman.com
        apiTokenSecretRef:
          name: cloudflare-api-token-secret
          key: api-token